class KeralaColleges {
  static const List<String> list = [
    "Ilahia College of Engineering and Technology, Moovattupuzha",
    "College of Engineering Trivandrum (CET)",
    "TKM College of Engineering, Kollam",
    "Government Engineering College (GEC), Thrissur",
    "NSS College of Engineering, Palakkad",
    "Mar Athanasius College of Engineering (MACE), Kothamangalam",
    "Rajiv Gandhi Institute of Technology (RIT), Kottayam",
    "Government College of Engineering, Kannur",
    "Government Engineering College, Barton Hill, Trivandrum",
    "Model Engineering College (MEC), Thrikkakara",
    "Sree Chitra Thirunal College of Engineering (SCT), Trivandrum",
    "Cochin University of Science and Technology (CUSAT), Kochi",
    "Rajagiri School of Engineering & Technology (RSET), Kochi",
    "Federal Institute of Science and Technology (FISAT), Angamaly",
    "Muthoot Institute of Technology and Science (MITS), Ernakulam",
    "Saintgits College of Engineering, Kottayam",
    "Amal Jyothi College of Engineering, Kanjirappally",
    "Mar Baselios College of Engineering and Technology (MBCET), Trivandrum",
    "Vidya Academy of Science and Technology (VAST), Thrissur",
    "SCMS School of Engineering and Technology (SSET), Kochi",
    "LBS College of Engineering, Kasaragod",
    "LBS Institute of Technology for Women, Poojappura",
    "Government Engineering College, Kozhikode",
    "Government Engineering College, Idukki",
    "Government Engineering College, Palakkad (Sreekrishnapuram)",
    "Government Engineering College, Wayanad",
    "Marian Engineering College, Trivandrum",
    "Mohandas College of Engineering and Technology, Nedumangad",
    "Sree Buddha College of Engineering, Alappuzha",
    "Viswajyothi College of Engineering and Technology, Vazhakulam",
    "Adi Shankara Institute of Engineering and Technology, Kalady",
    "Toc H Institute of Science and Technology, Ernakulam",
    "Vimal Jyothi Engineering College, Kannur",
    "Other/Not Listed"
  ];
}
